from setuptools import setup

setup(name='rampage',
      version='0.1.1',
      description='An arbitrary waveform builder and a control system for ultra-cold atom and ion trap experiments',
      classifiers=['Development Status :: 3 - Alpha',
                   'Environment :: X11 Applications :: Qt',
                   'Intended Audience :: Science/Research',
                   'License :: OSI Approved :: MIT License',
                   'Operating System :: OS Independent',
                   'Programming Language :: Python :: 2.7',
                   'Topic :: Multimedia :: Graphics :: Viewers',
                   'Topic :: Scientific/Engineering :: Physics',
                   'Topic :: Scientific/Engineering :: Visualization'],
      url='http://github.com/shreyaspotnis/rampage',
      author='Shreyas Potnis',
      author_email='shreyaspotnis@gmail.com',
      license='MIT',
      packages=['rampage'],
      install_requires=['pyqtgraph', 'numpy', 'pyzmq'],
      include_package_data=True,
      zip_safe=False)
